routes/web.php
<?php

Route::get('/', 'InicioController@site')->name('homepage');
Route::get('/entrar', 'InicioController@index')->name('inicio');
Route::post('/fazer-login', 'LoginController@doLogin')->name('login.usuario');
Route::post('/sair','LoginController@doLogout')->name('fazer.logout');
Route::group(['prefix' => 'restrito', 'middleware' => 'verifica-permissao'], function () {
    Route::get('/','InicioController@painel')->name('painel.controle');
    Route::resource('bairros','BairroController');
    Route::resource('ruas', 'RuaController');
    Route::resource('ubs', 'UbsController');
    Route::resource('noticias', 'NoticiasController');
    Route::resource('pessoas', 'PessoasController');
    Route::resource('servicos', 'ServicosController');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('noticia/{noticia}', 'NoticiasController@show')->name('noticia.show');
Route::get('noticias/ver-noticias','NoticiasController@exibirTodasNotícias')->name('noticias.all');
Route::get('unidade/{ubs}','UbsController@show')->name('unidade.show');
Route::get('busca-ubs','InicioController@buscaUbs')->name('ubs.seach');
Route::get('search/{unidade}', 'UbsController@searchUnidade')->name('search.unidade');

app/Models/Ubs.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Ubs extends Model
{
    protected $guarded = [];

    public function pessoas()
    {
        return $this->hasMany(Pessoa::class,'ubs_id');
    }

    public function rua()
    {
        return $this->belongsTo(Rua::class)->with('bairro');
    }

    public function servicos()
    {
        return $this->belongsToMany(Servico::class, 'ubs_servicos');
    }
}

app/Http/Controllers/UbsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\UbsRequest;
use App\Repositories\Ubs\UbsRepositoryEloquent;
use App\Services\UbsService;
use App\Services\RuasService;
use App\Services\ServicosService;

class UbsController extends Controller
{
    private $ubsRepository;
    private $ubsService;
    private $ruasService;
    private $servicosService;

    public function __construct(UbsRepositoryEloquent $ubsRepository, UbsService $ubsService, RuasService $ruasService, ServicosService $servicosService)
    {
        $this->ubsRepository = $ubsRepository;
        $this->ubsService = $ubsService;
        $this->ruasService = $ruasService;
        $this->servicosService = $servicosService;
    }

    public function index()
    {
        $unidades = $this->ubsService->listaUbs();

        return view('restrito.ubs.index', compact('unidades'));
    }

    public function create()
    {
        $arrayRuas = array();
        $ruas = $this->ruasService->listaRuas();
        foreach ($ruas as $rua) {
            $arrayRuas[$rua->id] = $rua->nome_rua . " - " . $rua->bairro->nome_bairro;
        }
        
        $servicos = $this->servicosService->listaTodosServicos();

        return view('restrito.ubs.form', compact('arrayRuas', 'servicos'));
    }

    public function store(UbsRequest $request)
    {
        $salvar = $this->ubsService->salvar($request);

        if ($salvar) {
            \Session::flash('success', 'Salvo com sucesso');
            return redirect()->route('ubs.index');
        }
    }

    public function show($unidade)
    {
        $unidade = $this->ubsService->exibirInformacoesUnidade($unidade);
    
        return response()->json($unidade, 200);
    }

    public function edit($id)
    {
        $arrayRuas = array();
        $ruas = $this->ruasService->listaRuas();
        foreach ($ruas as $rua) {
            $arrayRuas[$rua->id] = $rua->nome_rua . " - " . $rua->bairro->nome_bairro;
        }

        $unidade = $this->ubsService->buscaUbs($id);
        $servicos = $this->servicosService->listaTodosServicos();

        return view('restrito.ubs.form', compact('unidade', 'arrayRuas', 'servicos'));
    }

    public function update(UbsRequest $request, $id)
    {
        $update = $this->ubsService->update($request, $id);

        if ($update) {
            \Session::flash('success', 'Cadastro atualizado');
            return redirect()->route('ubs.index');
        }
    }

    public function destroy($id)
    {
        //
    }

    public function searchUnidade($pesquisa) 
    {
        $unidade = $this->ubsService->pesquisaUnidades($pesquisa);

        return $unidade;
    }
}

resources/views/restrito/ubs/form.blade.php
@extends('adminlte::page')
@section('title', 'Restrito :: UBS')

@section('content_header')
    <h1>Formulario de cadastro de Unidades Básicas de Saúde</h1>
@stop

@section('content')
    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-lg-12">
                    @if (isset($unidade))
                        {!! Form::model($unidade,['method' => 'PATCH','route' => ['ubs.update',$unidade->id], 'enctype' => 'multipart/form-data']) !!}
                    @else
                        {!! Form::open(['route' => 'ubs.store', 'enctype' => 'multipart/form-data']) !!}
                    @endif
                        <div class="form-group">
                            {!! Form::label('nome_ubs', 'Nome da lotação') !!}
                            {!! Form::text('nome_ubs', null, ['class' => 'form-control', 'placeholder' => 'Nome do Unidade']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('exibir_tela_inicial', 'Exibir na tela inicial?') !!}
                            <div class="row">
                                <div class="form-group col-md-1">
                                    {!! Form::radio('exibir_tela_inicial', 's', null) !!} Sim
                                </div>
                                <div class="form-group col-md-11">
                                    {!! Form::radio('exibir_tela_inicial', 'n', null) !!} Não
                                </div>
                            </div>    
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('rua_id', 'Rua') !!}
                            {!! Form::select('rua_id', $arrayRuas, null, ['class' => 'form-control', 'placeholder' => 'Escolha a rua']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('numero', 'Número') !!}
                            {!! Form::text('numero', null, ['class' => 'form-control', 'placeholder' => 'Número']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('servicos','Selecione os serviços') !!}
                            {!! Form::select('servicos[]',$servicos, null, ['class' => 'form-control servicos', 'multiple' => 'multiple']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('imagem', 'Imagem da unidade') !!}
                            {!! Form::file('imagem', null) !!}
                        </div>
                        {!! Form::submit('Salvar', ['class' => 'btn btn-success btn-sm']) !!}
                    {!! Form::close() !!}      
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/restrito/ubs/index.blade.php
@extends('adminlte::page')
@section('title', 'Restrito :: UBS')

@section('content_header')
    <h1>Lista de Unidades Básicas de Saúde - UBS</h1>
@stop

@section('content')
    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <a href="{{ route('ubs.create') }}" class="btn btn-primary btn-sm">Novo registro</a>
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <table class="table table-responsive datatable">
                        <thead>
                            <tr>
                                <th>Ações</th>
                                <th>Nome da Unidade</th>
                                <th>Endereço</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($unidades as $unidade)
                                <tr>
                                    <td>
                                        <a href="{{ route('ubs.edit', $unidade->id) }}" class="btn btn-default">Editar</a>
                                    </td>        
                                    <td>{{ $unidade->nome_ubs }}</td>
                                    <td>{{ $unidade->rua->nome_rua }}, {{ $unidade->numero }} - {{ $unidade->rua->bairro->nome_bairro }}</td>
                                @empty
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {{ $unidades->links() }}
                </div>
            </div>
        </div>
    </div>
@stop