routes/web.php
<?php

Route::get('/', 'InicioController@site')->name('homepage');
Route::get('/entrar', 'InicioController@index')->name('inicio');
Route::post('/fazer-login', 'LoginController@doLogin')->name('login.usuario');
Route::post('/sair','LoginController@doLogout')->name('fazer.logout');
Route::group(['prefix' => 'restrito', 'middleware' => 'verifica-permissao'], function () {
    Route::get('/','InicioController@painel')->name('painel.controle');
    Route::resource('bairros','BairroController');
    Route::resource('ruas', 'RuaController');
    Route::resource('ubs', 'UbsController');
    Route::resource('noticias', 'NoticiasController');
    Route::resource('pessoas', 'PessoasController');
    Route::resource('servicos', 'ServicosController');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('noticia/{noticia}', 'NoticiasController@show')->name('noticia.show');
Route::get('noticias/ver-noticias','NoticiasController@exibirTodasNotícias')->name('noticias.all');
Route::get('unidade/{ubs}','UbsController@show')->name('unidade.show');
Route::get('busca-ubs','InicioController@buscaUbs')->name('ubs.seach');
Route::get('search/{unidade}', 'UbsController@searchUnidade')->name('search.unidade');

app/Models/Pessoa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Pessoa extends Model
{
    protected $guarded = [];

    public function ubs()
    {
        return $this->belongsTo(Ubs::class,'ubs_id');
    }
}

app/Http/Controllers/PessoasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\PessoaService;
use App\Services\UbsService;

class PessoasController extends Controller
{
    private $pessoaService;
    private $ubsService;

    public function __construct(PessoaService $pessoaService, UbsService $ubsService)
    {
        $this->pessoaService = $pessoaService;
        $this->ubsService = $ubsService;
    }

    public function index()
    {
        $pessoas = $this->pessoaService->listaPessoas();

        return view('restrito.pessoas.index', compact('pessoas'));
    }
    
    public function create()
    {
        $cargos = $this->cargos();
        $ubs = $this->ubsService->listaUbs()->pluck('nome_ubs', 'id');
        return view('restrito.pessoas.form', compact('ubs', 'cargos'));
    }

    public function store(Request $request)
    {
        $salvar = $this->pessoaService->salvar($request);

        if ($salvar) {
            \Session::flash('success','Pessoa cadastrada com sucesso');
            return redirect()->route('pessoas.index');
        }
    }

    public function edit($id)
    {
        $pessoa = $this->pessoaService->pessoa($id);
        $cargos = $this->cargos();
        $ubs = $this->ubsService->listaUbs()->pluck('nome_ubs', 'id');

        return view('restrito.pessoas.form', compact('ubs', 'cargos', 'pessoa'));
    }

    public function update(Request $request, $id)
    {
        // dd($request->all());
        $update = $this->pessoaService->update($request, $id);
        
        if ($update) {
            \Session::flash('success','Registro alterado com sucesso');
            return redirect()->route('pessoas.index');
        }
    }

    public function destroy($id)
    {
        
    }

    public function cargos()
    {
        $cargos = [
            'Auxiliar Administrativo' => 'Auxiliar Administrativo',
            'Digitador (a)' => 'Digitador (a)',
            'Coordenador da Vigilância sanitária' => 'Coordenação da Vigilância sanitária',
            'Coordenador de Projetos' => 'Coordenador de Projetos',
            'Coordenador de Sistema da Informação' => 'Coordenador de Sistema da Informação',
            'Coordenador (a) da Atenção Básica' => 'Coordenador (a) da Atenção Básica',
            'Motorista' => 'Motorista',
            'Recepcionista' => 'Recepcionista',
            'Secretário (a) de Saúde' => 'Secretário (a) de Saúde',
            'Serviços Gerais' => 'Serviços Gerais',
            'Técnico Bolsa família' => 'Técnico Bolsa família'
        ];

        return $cargos;
    }
}

resources/views/restrito/pessoas/form.blade.php
@extends('adminlte::page')
@section('title', 'Restrito :: Pessoas')

@section('content_header')
    <h1>Formulario de cadastro de pessoas</h1>
@stop

@section('content')
    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-lg-12">
                    @if (isset($pessoa))
                        {!! Form::model($pessoa,['method' => 'PATCH','route' => ['pessoas.update',$pessoa->id], 'enctype' => 'multipart/form-data']) !!}
                    @else
                        {!! Form::open(['route' => 'pessoas.store', 'enctype' => 'multipart/form-data']) !!}
                    @endif
                        <div class="form-group">
                            {!! Form::label('nome', 'Nome') !!}
                            {!! Form::text('nome', null, ['class' => 'form-control', 'placeholder' => 'Nome completo']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('cargo', 'Bairro') !!}
                            {!! Form::select('cargo', $cargos, null, ['class' => 'form-control', 'placeholder' => 'Selecione cargo...']) !!}
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('ubs_id', 'UBS') !!}
                            {!! Form::select('ubs_id', $ubs, null, ['class' => 'form-control', 'placeholder' => 'Selecione a UBS...']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('imagem', 'Imagem') !!}
                            {!! Form::file('imagem', null, ['class' => 'form-control']) !!}
                            @if (isset($pessoa))
                                <img class="img img-responsive" src="{{ asset('uploads/'.$pessoa->imagem) }}" alt="">
                            @endif
                        </div>
                        
                        {!! Form::submit('Salvar', ['class' => 'btn btn-success btn-sm']) !!}
                    {!! Form::close() !!}      
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/restrito/pessoas/index.blade.php
@extends('adminlte::page')
@section('title', 'Restrito :: pessoas')

@section('content_header')
    <h1>Lista de Pessoas</h1>
@stop

@section('content')
    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <a href="{{ route('pessoas.create') }}" class="btn btn-primary btn-sm">Novo registro</a>
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <table class="table table-responsive datatable">
                        <thead>
                            <tr>
                                <th>Ações</th>
                                <th>Nome</th>
                                <th>Cargo</th>
                                <th>UBS</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($pessoas as $pessoa)
                                <tr>
                                    <td>
                                        <a href="{{ route('pessoas.edit', $pessoa->id) }}" class="btn btn-default btn-sm">Editar</a>
                                    </td>        
                                    <td>{{ $pessoa->nome }}</td>
                                    <td>{{ $pessoa->cargo }}</td>
                                    <td>{{ $pessoa->ubs->nome_ubs }}</td>
                                @empty
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {{ $pessoas->links() }}
                </div>
            </div>
        </div>
    </div>
@stop