routes/web.php
<?php

Route::get('/', 'InicioController@site')->name('homepage');
Route::get('/entrar', 'InicioController@index')->name('inicio');
Route::post('/fazer-login', 'LoginController@doLogin')->name('login.usuario');
Route::post('/sair','LoginController@doLogout')->name('fazer.logout');
Route::group(['prefix' => 'restrito', 'middleware' => 'verifica-permissao'], function () {
    Route::get('/','InicioController@painel')->name('painel.controle');
    Route::resource('bairros','BairroController');
    Route::resource('ruas', 'RuaController');
    Route::resource('ubs', 'UbsController');
    Route::resource('noticias', 'NoticiasController');
    Route::resource('pessoas', 'PessoasController');
    Route::resource('servicos', 'ServicosController');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('noticia/{noticia}', 'NoticiasController@show')->name('noticia.show');
Route::get('noticias/ver-noticias','NoticiasController@exibirTodasNotícias')->name('noticias.all');
Route::get('unidade/{ubs}','UbsController@show')->name('unidade.show');
Route::get('busca-ubs','InicioController@buscaUbs')->name('ubs.seach');
Route::get('search/{unidade}', 'UbsController@searchUnidade')->name('search.unidade');

app/Models/Noticia.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Noticia extends Model
{
    protected $guarded = [];   
}

app/Http/Controllers/NoticiasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\NoticiaService;
use App\Services\UbsService;
use App\Services\ServicosService;

class NoticiasController extends Controller
{
    private $noticiaService;
    private $ubsService;
    private $servicosService;

    public function __construct(NoticiaService $noticiaService, UbsService $ubsService, ServicosService $servicosService)
    {
        $this->noticiaService = $noticiaService;
        $this->ubsService = $ubsService;
        $this->servicosService = $servicosService;
    }

    public function index()
    {
        $noticias = $this->noticiaService->listaNoticias();

        return view('restrito.noticias.index', compact('noticias'));
    }

    public function create()
    {
        return view('restrito.noticias.form');
    }

    public function store(Request $request)
    {
        $salvar = $this->noticiaService->salvar($request);

        if($salvar){
            \Session::flash('success','Notícia cadastrada com sucesso');
            return redirect()->route('noticias.index');
        }
    }

    public function show($noticia)
    {
        $noticia = $this->noticiaService->exibirNoticia($noticia);
        $secretaria = $this->ubsService->buscaSecretariaSaudePaginaInicial();
        $servicos = $this->servicosService->servicosPaginaInicial();
        $page = $noticia->titulo_noticia;

        return view('site.noticias.show', compact('noticia', 'page', 'secretaria', 'servicos'));
    }

    public function edit($id)
    {
         $noticia = $this->noticiaService->noticia($id);   
         
         return view('restrito.noticias.form', compact('noticia'));
    }

    public function update(Request $request, $id)
    {
        $update = $this->noticiaService->update($request, $id);

        if ($update) {
            \Session::flash('success', 'Cadastro atualizado com sucesso');

            return redirect()->route('noticias.index');
        }
    }

    public function destroy($id)
    {
        //
    }

    public function exibirTodasNotícias()
    {
        $noticias = $this->noticiaService->listaNoticias();
        $secretaria = $this->ubsService->buscaSecretariaSaudePaginaInicial();
        $servicos = $this->servicosService->servicosPaginaInicial();
        $page = 'Prefeitura de Jutaí :: Notícias';

        return view('site.noticias.index', compact('secretaria', 'page', 'noticias', 'servicos'));
    }
}

resources/views/restrito/noticias/form.blade.php
@extends('adminlte::page')
@section('title', 'Restrito :: notícias')

@section('content_header')
    <h1>Formulario de cadastro de nottícias</h1>
@stop

@section('content')
    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-lg-12">
                    @if (isset($noticia))
                        {!! Form::model($noticia,['method' => 'PATCH','route' => ['noticias.update',$noticia->id], 'enctype' => 'multipart/form-data']) !!}
                    @else
                        {!! Form::open(['route' => 'noticias.store', 'enctype' => 'multipart/form-data']) !!}
                    @endif
                        <div class="form-group">
                            {!! Form::label('titulo_noticia', 'Título') !!}
                            {!! Form::text('titulo_noticia', null, ['class' => 'form-control', 'placeholder' => 'Título da notícia']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('conteudo_noticia', 'Conteúdo') !!}
                            {!! Form::textarea('conteudo_noticia', null, ['class' => 'form-control', 'placeholder' => 'Conteúdo da notícia']) !!}
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('image_noticia', 'Imagem') !!}
                            {!! Form::file('image_noticia', null, ['class' => 'form-control']) !!}
                            @if (isset($noticia))
                                <img class="img img-responsive" src="{{ asset('uploads/'.$noticia->image_noticia) }}" alt="">
                            @endif
                        </div>
                        {!! Form::submit('Salvar', ['class' => 'btn btn-success btn-sm']) !!}
                    {!! Form::close() !!}      
                </div>
            </div>
        </div>
    </div>
@stop
@push('js')
    <script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
    <script>
        window.onload = function()  {
            CKEDITOR.replace( 'conteudo_noticia' );
        };
    </script>
@endpush

resources/views/restrito/noticias/index.blade.php
@extends('adminlte::page')
@section('title', 'Restrito :: notícias')

@section('content_header')
    <h1>Lista de notícias</h1>
@stop

@section('content')
    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <a href="{{ route('noticias.create') }}" class="btn btn-primary btn-sm">Novo registro</a>
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <table class="table table-responsive datatable">
                        <thead>
                            <tr>
                                <th>Ações</th>
                                <th>Título da notícia</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($noticias as $noticia)
                                <tr>
                                    <td>
                                        <a href="{{ route('noticias.edit', $noticia->id) }}" class="btn btn-default btn-sm">Editar</a>
                                    </td>        
                                    <td>{{ $noticia->titulo_noticia }}</td>
                                @empty
                                </tr>
                            @endforelse

                        </tbody>
                    </table>
                            {{ $noticias->links() }}
                </div>
            </div>
        </div>
    </div>
@stop