routes/web.php
<?php

Route::get('/', 'InicioController@site')->name('homepage');
Route::get('/entrar', 'InicioController@index')->name('inicio');
Route::post('/fazer-login', 'LoginController@doLogin')->name('login.usuario');
Route::post('/sair','LoginController@doLogout')->name('fazer.logout');
Route::group(['prefix' => 'restrito', 'middleware' => 'verifica-permissao'], function () {
    Route::get('/','InicioController@painel')->name('painel.controle');
    Route::resource('bairros','BairroController');
    Route::resource('ruas', 'RuaController');
    Route::resource('ubs', 'UbsController');
    Route::resource('noticias', 'NoticiasController');
    Route::resource('pessoas', 'PessoasController');
    Route::resource('servicos', 'ServicosController');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('noticia/{noticia}', 'NoticiasController@show')->name('noticia.show');
Route::get('noticias/ver-noticias','NoticiasController@exibirTodasNotícias')->name('noticias.all');
Route::get('unidade/{ubs}','UbsController@show')->name('unidade.show');
Route::get('busca-ubs','InicioController@buscaUbs')->name('ubs.seach');
Route::get('search/{unidade}', 'UbsController@searchUnidade')->name('search.unidade');

app/Models/Rua.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Rua extends Model
{
    protected $fillable = ['nome_rua', 'bairro_id'];

    public function bairro()
    {
    	return $this->belongsTo(Bairro::class);
    }
    public function ubs()
    {
        return $this->hasOne(Ubs::class);
    }
}

app/Http/Controllers/RuaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\Rua\RuaRepositoryEloquent;
use App\Services\RuasService;
use App\Services\BairrosService;

class RuaController extends Controller
{
    private $ruaRepository;
    private $ruasService;
    private $bairrosService;

    public function __construct(RuaRepositoryEloquent $ruaRepository, RuasService $ruasService, BairrosService $bairrosService)
    {
        $this->ruaRepository = $ruaRepository;
        $this->ruasService = $ruasService;
        $this->bairrosService = $bairrosService;
    }

    public function index()
    {
        $ruas = $this->ruasService->listaRuas();

        return view('restrito.ruas.index', compact('ruas'));
    }

    public function create()
    {
        $bairros = $this->bairrosService->lista_bairros();

        return view('restrito.ruas.form', compact('bairros'));
    }

    public function store(Request $request)
    {
        $salvar = $this->ruasService->salvar($request);

        if($salvar){
            \Session::flash('success','Rua cadastrada com sucesso');
            return redirect()->route('ruas.index');
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
         $rua = $this->ruasService->rua($id);   
         $bairros = $this->bairrosService->lista_bairros();
         
         return view('restrito.ruas.form', compact('rua', 'bairros'));
    }

    public function update(Request $request, $id)
    {
        $update = $this->ruasService->update($request, $id);

        if ($update) {
            \Session::flash('success', 'Cadastro atualizado com sucesso');

            return redirect()->route('ruas.index');
        }
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/restrito/ruas/form.blade.php
@extends('adminlte::page')
@section('title', 'Restrito :: Ruas')

@section('content_header')
    <h1>Formulario de cadastro de ruas</h1>
@stop

@section('content')
    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-lg-12">
                    @if (isset($rua))
                        {!! Form::model($rua,['method' => 'PATCH','route' => ['ruas.update',$rua->id]]) !!}
                    @else
                        {!! Form::open(['route' => 'ruas.store']) !!}
                    @endif
                        <div class="form-group">
                            {!! Form::label('nome_rua', 'Bairro') !!}
                            {!! Form::text('nome_rua', null, ['class' => 'form-control', 'placeholder' => 'Nome da rua']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('bairro_id', 'Bairro') !!}
                            {!! Form::select('bairro_id', $bairros, null, ['class' => 'form-control', 'placeholder' => 'Selecione o bairro']) !!}
                        </div>
                        {!! Form::submit('Salvar', ['class' => 'btn btn-success btn-sm']) !!}
                    {!! Form::close() !!}      
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/restrito/ruas/index.blade.php
@extends('adminlte::page')
@section('title', 'Restrito :: ruas')

@section('content_header')
    <h1>Lista de Ruas</h1>
@stop

@section('content')
    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <a href="{{ route('ruas.create') }}" class="btn btn-primary btn-sm">Novo registro</a>
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <table class="table table-responsive datatable">
                        <thead>
                            <tr>
                                <th>Ações</th>
                                <th>Nome da rua</th>
                                <th>Bairro</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($ruas as $rua)
                                <tr>
                                    <td>
                                        <a href="{{ route('ruas.edit', $rua->id) }}" class="btn btn-default btn-sm">Editar</a>
                                    </td>        
                                    <td>{{ $rua->nome_rua }}</td>
                                    <td>{{ $rua->bairro->nome_bairro }}</td>
                                @empty
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {{ $ruas->links() }}
                </div>
            </div>
        </div>
    </div>
@stop